### ISSUE TITLE
Page Übergreifend

### ISSUE THREAD

**Issue by sobius96** [sobius96/sobius96.github.io#2]
# ToDo

- [x] Header: Links müssen auf Vollständigkeit und Sinnhaftigkeit geprüft werden
- [x] Header: Logo muss als SVG eingefügt werden
- [x] Header: Style muss angepasst werden
___
- [x] Footer: Inhalt muss sich überlegt werden
- [x] Footer: Inhalt muss eingefügt werden
- [x] Footer: Style muss angepasst werden
___
- [x] Logo muss als Icon in Tab Titel eingefügt werden
- [x] Layout muss angepasst werden
- [x] Farben müssen angepasst werden 
___
- [x] Bio Images müssen erstellt werden (ca 4 - 6)
- [x] benannt **img_x.jpg** (x ist dann eine Zahl von 1 bis 4 oder 6)

**Comment by zinni0** [comment]
finished, commits had no signature
