### ISSUE TITLE
Index Page - index.php

### ISSUE THREAD

**Issue by sobius96** [sobius96/sobius96.github.io#3]
# ToDo
- [x] HREF Links auf Richtigkeit überprüfen
- [x] auf Vollständigkeit prüfen
___
- [x] PHP Tag einfügen
- [x] PHP basierender Inhalt muss sich überlegt werden
- [x] PHP basierender Inhalt braucht ein Layout/Design
___
- [x] show full profile

**Comment by zinni0** [comment]
finished
