### ISSUE TITLE
login.php

### ISSUE THREAD

**Issue by sobius96** [sobius96/sobius96.github.io#4]
# ToDo
- [x] Verbindung zur DB herstellen
- [x] Passwort zu Hashwert umwandeln
- [x] SQL Injection durch Eingaben verhindern
- [x] Login Daten abfragen
- [x] wenn Erfolgreich Cookie setzen
- [x] wenn nicht Error Page anzeigen

**Comment by zinni0** [comment]
everything finished (No errorpage, rediret to login.html)
